{
 "title": "Computer Vision - Cats & Dogs (Workshop)",
 "tags": [
  "mlops",
  "computer-vision",
  "workshop"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "inferencetime__ms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cv_last_inference_seconds{instance=\"cv_app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🗄️ Statut Base de Données",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cv_database_connected" }
   ]
  },
  {
   "title": "Requêtes HTTP (GET vs POST)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (http_requests_total{instance=\"cv_app:8000\"})",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}